services:
  bot:
    image: tempestmon/mopsorez_bot:latest
    restart: unless-stopped
    network_mode: host
    env_file: .env
    environment:
      - RUST_LOG=trace
    volumes:
      - ./sounds:/app/sounds:ro
      - bot_data:/app/data

volumes:
  bot_data:
